version: '3'

services:
    db:
        image: postgres
        container_name: postgres
        command: "postgres -c 'max_connections=500'"
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: scheduler
            POSTGRES_USER: scheduler
        restart: always
        ports: 
            - "5432:5432"
    web:
        build: .
        ports: 
            - "3000:3000"
        volumes:
            - .:/usr/src/app
        command: bundle exec rails s -b 0.0.0.0
        environment:
            DB_HOST: db
            DB_NAME: scheduler
            DB_USERNAME: scheduler
            DB_PASSWORD: 123456
        depends_on:
            - db
volumes:
    web:
    pgdata: 
    
networks:
    default:
        name: scheduler